/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait OrganizationInviteLinksApi: Send + Sync {
    /// POST /organizations/{orgId}/invite-link
    async fn create<'a>(
        &self,
        org_id: uuid::Uuid,
        create_organization_invite_link_request_model: Option<
            models::CreateOrganizationInviteLinkRequestModel,
        >,
    ) -> Result<(), Error>;
}

pub struct OrganizationInviteLinksApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OrganizationInviteLinksApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl OrganizationInviteLinksApi for OrganizationInviteLinksApiClient {
    async fn create<'a>(
        &self,
        org_id: uuid::Uuid,
        create_organization_invite_link_request_model: Option<
            models::CreateOrganizationInviteLinkRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/invite-link",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&create_organization_invite_link_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }
}
