/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Visitor};

use crate::models;
/// RevocationReason : The reason a user was revoked from an organization.
/// The reason a user was revoked from an organization.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum RevocationReason {
    Unknown,
    Manual,
    TwoFactorPolicyNonCompliance,
    OrganizationDataOwnershipPolicyNonCompliance,
    SingleOrgPolicyNonCompliance,

    /// Unknown value returned from the server. This is used to handle forward compatibility.
    __Unknown(i64),
}

impl RevocationReason {
    pub fn as_i64(&self) -> i64 {
        match self {
            Self::Unknown => 0,
            Self::Manual => 1,
            Self::TwoFactorPolicyNonCompliance => 2,
            Self::OrganizationDataOwnershipPolicyNonCompliance => 3,
            Self::SingleOrgPolicyNonCompliance => 4,
            Self::__Unknown(v) => *v,
        }
    }

    pub fn from_i64(value: i64) -> Self {
        match value {
            0 => Self::Unknown,
            1 => Self::Manual,
            2 => Self::TwoFactorPolicyNonCompliance,
            3 => Self::OrganizationDataOwnershipPolicyNonCompliance,
            4 => Self::SingleOrgPolicyNonCompliance,
            v => Self::__Unknown(v),
        }
    }
}

impl serde::Serialize for RevocationReason {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_i64(self.as_i64())
    }
}

impl<'de> serde::Deserialize<'de> for RevocationReason {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct RevocationReasonVisitor;

        impl Visitor<'_> for RevocationReasonVisitor {
            type Value = RevocationReason;

            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("an integer")
            }

            fn visit_i64<E: serde::de::Error>(self, v: i64) -> Result<Self::Value, E> {
                Ok(RevocationReason::from_i64(v))
            }

            fn visit_u64<E: serde::de::Error>(self, v: u64) -> Result<Self::Value, E> {
                Ok(RevocationReason::from_i64(v as i64))
            }
        }

        deserializer.deserialize_i64(RevocationReasonVisitor)
    }
}

impl std::fmt::Display for RevocationReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_i64())
    }
}
impl Default for RevocationReason {
    fn default() -> RevocationReason {
        Self::Unknown
    }
}
